# Generated by Django 5.0.6 on 2026-02-23 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movements', '0001_initial'),
        ('product_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='product_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='product_accounts.productaccount', verbose_name='Cuenta de productos'),
        ),
    ]
