# Generated by Django 5.0.6 on 2026-02-22 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movements', '0002_initial'),
        ('table_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='table_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='table_sessions.tablesession', verbose_name='Sesión de mesa'),
        ),
    ]
