# Generated by Django 5.0.6 on 2026-03-08 20:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('machines', '0002_initial'),
        ('movements', '0004_initial'),
        ('table_sessions', '0005_tablesession_paused_at_tablesession_time_stopped_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='machine',
        ),
        migrations.AddField(
            model_name='movement',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='movement',
            name='machine_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='machines.machinepayment', verbose_name='Pago de maquina'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='table_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='table_sessions.tablesession', verbose_name='Sesion de mesa'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador'),
        ),
    ]
