# Generated by Django 5.0.6 on 2026-02-23 21:23

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto abonado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Abono',
                'verbose_name_plural': 'Abonos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sesion', 'Sesion de Mesa'), ('cuenta', 'Cuenta de Productos')], max_length=10, verbose_name='Origen')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto original')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total abonado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de deuda')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago total')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'ordering': ['-created_at'],
            },
        ),
    ]
