# Generated by Django 5.0.6 on 2026-02-23 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_accounts', '0002_initial'),
        ('receivables', '0001_initial'),
        ('table_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables_collected', to=settings.AUTH_USER_MODEL, verbose_name='Cobrado por'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='product_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable', to='product_accounts.productaccount', verbose_name='Cuenta de productos'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='table_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable', to='table_sessions.tablesession', verbose_name='Sesion de mesa'),
        ),
        migrations.AddField(
            model_name='receivablepayment',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='receivables.receivable', verbose_name='Deuda'),
        ),
        migrations.AddField(
            model_name='receivablepayment',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
