# Generated by Django 5.0.6 on 2026-03-08 21:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('machines', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name'], 'verbose_name': 'Maquina', 'verbose_name_plural': 'Maquinas'},
        ),
        migrations.AlterModelOptions(
            name='machinepayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pago de Maquina', 'verbose_name_plural': 'Pagos de Maquinas'},
        ),
        migrations.AlterField(
            model_name='machine',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='machinepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='machinepayment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_payments', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='machinepayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='machinepayment',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='machines.machine'),
        ),
        migrations.AlterField(
            model_name='machinepayment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='machinepayment',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='machine_payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
