# Generated by Django 5.0.6 on 2026-02-22 23:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto en Sesión',
                'verbose_name_plural': 'Productos en Sesión',
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cierre')),
                ('time_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total tiempo')),
                ('products_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total productos')),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total general')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='clients.client', verbose_name='Cliente')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='tables.table', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Sesión de Mesa',
                'verbose_name_plural': 'Sesiones de Mesa',
                'ordering': ['-opened_at'],
            },
        ),
    ]
