# Generated by Django 5.0.6 on 2026-02-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_sessions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pausado en'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='time_stopped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tiempo detenido en'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='timer_status',
            field=models.CharField(choices=[('running', 'Corriendo'), ('paused', 'Pausado'), ('stopped', 'Tiempo detenido')], default='running', max_length=10, verbose_name='Estado cronometro'),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Segundos pausados acumulados'),
        ),
    ]
