# Generated by Django 5.0.6 on 2026-02-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_sessions', '0003_tablesession_paused_at_tablesession_time_stopped_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablesession',
            name='paused_at',
        ),
        migrations.RemoveField(
            model_name='tablesession',
            name='time_stopped_at',
        ),
        migrations.RemoveField(
            model_name='tablesession',
            name='timer_status',
        ),
        migrations.RemoveField(
            model_name='tablesession',
            name='total_paused_seconds',
        ),
    ]
