# Generated by Django 5.0.6 on 2026-03-08 21:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('table_sessions', '0005_tablesession_paused_at_tablesession_time_stopped_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionproduct',
            options={},
        ),
        migrations.AddField(
            model_name='tablesession',
            name='client_alias',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de paso'),
        ),
        migrations.AlterField(
            model_name='sessionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AlterField(
            model_name='sessionproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sessionproduct',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_products', to='table_sessions.tablesession'),
        ),
        migrations.AlterField(
            model_name='sessionproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='products_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='time_stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='time_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='timer_status',
            field=models.CharField(choices=[('running', 'Corriendo'), ('paused', 'Pausado'), ('stopped', 'Tiempo detenido')], default='running', max_length=10),
        ),
        migrations.AlterField(
            model_name='tablesession',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
