# Generated by Django 5.0.6 on 2026-02-22 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad ingresada')),
                ('stock_before', models.PositiveIntegerField(verbose_name='Stock antes')),
                ('stock_after', models.PositiveIntegerField(verbose_name='Stock después')),
                ('notes', models.TextField(blank=True, verbose_name='Notas / Proveedor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Entrada de Stock',
                'verbose_name_plural': 'Entradas de Stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
