# Generated by Django 5.0.6 on 2026-03-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_type',
            field=models.CharField(choices=[('tres_bandas', '3 Bandas'), ('libre', 'Libre'), ('pool', 'Pool')], default='libre', max_length=20, verbose_name='Tipo de mesa'),
        ),
    ]
