# Generated by Django 5.0.6 on 2026-02-22 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productaccount',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='accountproduct',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_products', to='product_accounts.productaccount', verbose_name='Cuenta'),
        ),
    ]
