# Generated by Django 5.0.6 on 2026-03-08 21:15

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('product_accounts', '0002_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountproduct',
            options={},
        ),
        migrations.AddField(
            model_name='productaccount',
            name='client_alias',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de paso'),
        ),
        migrations.AlterField(
            model_name='accountproduct',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_products', to='product_accounts.productaccount'),
        ),
        migrations.AlterField(
            model_name='accountproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AlterField(
            model_name='accountproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accountproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productaccount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_accounts', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='productaccount',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productaccount',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='productaccount',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productaccount',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productaccount',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
