# Generated by Django 5.0.6 on 2026-03-08 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio de sesion')),
                ('logout_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de sesion')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesion de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'ordering': ['-login_at'],
            },
        ),
    ]
